file_format: "1"
id: yarisugi
name: Yarisugi
type: shield
url: https://github.com/eggdale/yarisugi
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - yarisugi_left
  - yarisugi_right