manifest:
  remotes:
    # - name: zmkfirmware
    #   url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: akscram
      url-base: https://github.com/akscram
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
    #   import: app/west.yml
    # - name: cirque-input-module
    #   remote: petejohanson
    #   revision: main
    - name: zephyr
      remote: akscram
      revision: driver-input-pinnacle
      import: app/west.yml
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll

  self:
    path: config
