file_format: "1"
id: chimera
name: Chimera
type: shield
url: https://github.com/eggdale/chimera
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - chimera_left
  - chimera_right